version: '3.3'

services:
  ruby_dev:
    build:
      context: .
      args:
        - BUNDLE_JOBS=15
        - BUNDLE_RETRY=2
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - PORT=${PORT}
    container_name: ruby_container
    ports:
      - '3000:3000'
    user: ruby
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
volumes:
  gems:
  postgres:
  node_modules:
  packs:
  rails_cache:
